# Generated by Django 5.2.5 on 2025-10-09 04:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_cart_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2025, 10, 9, 4, 52, 33, 914066, tzinfo=datetime.timezone.utc), unique=True),
            preserve_default=False,
        ),
    ]
