# Generated by Django 5.2.5 on 2025-10-09 05:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2025, 10, 9, 5, 3, 53, 108516, tzinfo=datetime.timezone.utc), unique=True),
            preserve_default=False,
        ),
    ]
